version: '3.7'

services:
    coec-db:
        image: mysql/mysql-server:latest
        container_name: coec-database
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD_ROOT}"
            - "MYSQL_DATABASE=${DB_NAME}"
            - "MYSQL_USER=${DB_USERNAME}"
            - "MYSQL_PASSWORD=${DB_PASSWORD}"
        networks:
            - internal
        volumes:
            - coec-db:/var/lib/mysql
        restart: always
        
    coec-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: coec-api
        environment:
            - "ENVIRONMENT=${ENVIRONMENT}"
            - "API_PORT=${API_PORT}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
            - "DB_HOST=coec-db"
            - "DB_PORT=3306"
            - "DB_NAME=${DB_NAME}"
            - "SECRET_AUTH=${SECRET_AUTH}"
            - "ETH_DEFAULT_ADMIN_PUBLIC=${ETH_DEFAULT_ADMIN_PUBLIC}"
            - "ETH_DEFAULT_ADMIN_PRIVATE=${ETH_DEFAULT_ADMIN_PRIVATE}"
            - "ETH_INFURA_SECRET=${ETH_INFURA_SECRET}"
            - "ETH_NETWORK=${ETH_NETWORK}"
            - "ETH_SMART_CONTRACT=${ETH_SMART_CONTRACT}"
        networks:
            - internal
        ports:
            - "${API_PORT}:${API_PORT}"
        expose:
            - "${API_PORT}"
        restart: always
        command: ./wait-for-it.sh -t 0 coec-db:3306 -- ./main
        
networks:
    internal:

volumes:
    coec-db: