version: '3.7'

services:

    openvino-db:
        image: mysql/mysql-server:latest
        container_name: database
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD_ROOT}"
            - "MYSQL_DATABASE=${DATABASE_NAME}"
            - "MYSQL_USER=${DATABASE_USERNAME}"
            - "MYSQL_PASSWORD=${DATABASE_PASSWORD}"
        networks:
            - internal
        volumes:
            - test-db:/var/lib/mysql
        restart: always
        
    openvino-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        environment:
            - "ENVIRONMENT=${ENVIRONMENT}"
            - "API_PORT=${API_PORT}"
            - "DATABASE_HOST=database"
            - "DATABASE_PORT=3306"
            - "DATABASE_DIALECT=mysql"
            - "DATABASE_NAME=${DATABASE_NAME}"
            - "DATABASE_CHARSET=${DATABASE_CHARSET}"
            - "DATABASE_USERNAME=${DATABASE_USERNAME}"
            - "DATABASE_PASSWORD=${DATABASE_PASSWORD}"
        networks:
            - internal
        ports:
            - "${API_PORT}:${API_PORT}"
        expose:
            - "${API_PORT}"
        restart: always
        
networks:
    internal:

volumes:
    test-db: