version: '3.7'

services:

    openvino-db:
        image: mysql/mysql-server:latest
        container_name: database
        ports:
            - 3306:3306
        expose:
            - 3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        networks:
            - internal
        volumes:
            - costaflores-db:/var/lib/mysql
        
    openvino-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api
        networks:
            - internal
        ports:
            - 3000:3000
        expose:
            - 3000
        
networks:
    internal:

volumes:
    costaflores-db: