version: '3'

services:

    openvino-db:
        image: mysql:8.0
        container_name: database
        ports:
            - 33060:3306
        environment:
            - "MYSQL_ROOT_PASSWORD=${PASSWORD_ADMIN}"
        volumes:
            - costaflores-db:/var/lib/mysql

    openvino-api:
        build: .
        container_name: api
        
volumes:
    costaflores-db:
